// Basic ZIP code to city/state mapping for common ZIP codes
// This serves as a fallback when external APIs are unavailable
export const zipCodeFallback: { [key: string]: { city: string; state: string } } = {
  // Major cities - you can expand this list
  "10001": { city: "New York", state: "NY" },
  "10002": { city: "New York", state: "NY" },
  "10003": { city: "New York", state: "NY" },
  "10004": { city: "New York", state: "NY" },
  "10005": { city: "New York", state: "NY" },
  "90210": { city: "Beverly Hills", state: "CA" },
  "90211": { city: "Beverly Hills", state: "CA" },
  "90212": { city: "Beverly Hills", state: "CA" },
  "33101": { city: "Miami Beach", state: "FL" },
  "33102": { city: "Miami Beach", state: "FL" },
  "60601": { city: "Chicago", state: "IL" },
  "60602": { city: "Chicago", state: "IL" },
  "60603": { city: "Chicago", state: "IL" },
  "77001": { city: "Houston", state: "TX" },
  "77002": { city: "Houston", state: "TX" },
  "77003": { city: "Houston", state: "TX" },
  "30301": { city: "Atlanta", state: "GA" },
  "30302": { city: "Atlanta", state: "GA" },
  "30303": { city: "Atlanta", state: "GA" },
  "85001": { city: "Phoenix", state: "AZ" },
  "85002": { city: "Phoenix", state: "AZ" },
  "85003": { city: "Phoenix", state: "AZ" },
  "19101": { city: "Philadelphia", state: "PA" },
  "19102": { city: "Philadelphia", state: "PA" },
  "19103": { city: "Philadelphia", state: "PA" },
  "02101": { city: "Boston", state: "MA" },
  "02102": { city: "Boston", state: "MA" },
  "02103": { city: "Boston", state: "MA" },
  "98101": { city: "Seattle", state: "WA" },
  "98102": { city: "Seattle", state: "WA" },
  "98103": { city: "Seattle", state: "WA" },
  "80201": { city: "Denver", state: "CO" },
  "80202": { city: "Denver", state: "CO" },
  "80203": { city: "Denver", state: "CO" },
  "20001": { city: "Washington", state: "DC" },
  "20002": { city: "Washington", state: "DC" },
  "20003": { city: "Washington", state: "DC" },
  "89101": { city: "Las Vegas", state: "NV" },
  "89102": { city: "Las Vegas", state: "NV" },
  "89103": { city: "Las Vegas", state: "NV" },
  "97201": { city: "Portland", state: "OR" },
  "97202": { city: "Portland", state: "OR" },
  "97203": { city: "Portland", state: "OR" },
  "63101": { city: "St. Louis", state: "MO" },
  "63102": { city: "St. Louis", state: "MO" },
  "63103": { city: "St. Louis", state: "MO" },
  "32801": { city: "Orlando", state: "FL" },
  "32802": { city: "Orlando", state: "FL" },
  "32803": { city: "Orlando", state: "FL" },
  "46201": { city: "Indianapolis", state: "IN" },
  "46202": { city: "Indianapolis", state: "IN" },
  "46203": { city: "Indianapolis", state: "IN" },
  "43201": { city: "Columbus", state: "OH" },
  "43202": { city: "Columbus", state: "OH" },
  "43203": { city: "Columbus", state: "OH" },
  "26501": { city: "Morgantown", state: "WV" },
  "26502": { city: "Morgantown", state: "WV" },
  "45068": { city: "Waynesville", state: "OH" },
  "45385": { city: "Xenia", state: "OH" },
  "50427": { city: "Chapin", state: "IA" },
  "17113": { city: "Harrisburg", state: "PA" },
  "46885": { city: "Fort Wayne", state: "IN" },
  "61702": { city: "Bloomington", state: "IL" },
  "61710": { city: "Bloomington", state: "IL" },
  "26531": { city: "Dellslow", state: "WV" },
}
